import raw from "./data/demo.json";
import type { NoteKey } from "./i18n/en";

export type Outcome = "repair" | "refuse";
export type StageKey = "fail" | "prep" | "diag" | "patch" | "verify" | "run" | "end";
export type StepKind = "log" | "diff" | "fail" | "healed" | "refused";
export type Reason = "ambiguous_target" | "loop_cap_reached" | "guardrail_violation" | "insufficient_evidence";

/** Real, language-neutral data generated by scripts/build_data.py. */
export type ScenarioData = {
  name: string;
  class: string;
  expected: Outcome;
  failing: string;
  spec: string;
  patch: string;
  patchFile: string;
  failure: string;
  pre: { error: string; dom: unknown[] };
};
export const scenarioData = raw as Record<string, ScenarioData>;

export type Step = { stage: StageKey; kind: StepKind; log: string; note?: NoteKey };
type Run = {
  outcome: Outcome;
  reason?: Reason;
  // True only for a run that was actually observed (id-rename: README "Demo", NVIDIA NIM).
  observed?: boolean;
  // Present for scenarios shown in the player; benchmark-only scenarios carry just the outcome.
  steps?: Step[];
};

// Simulated engine runs, shaped after the real log events and the refusal-reason branches in
// app/graph.py. The player shows the first group; the rest only feed the benchmark example.
export const RUNS = {
  "id-rename": {
    outcome: "repair",
    observed: true,
    steps: [
      { stage: "diag", kind: "log", log: "diagnoser_finished\n#submit-btn → id renamed (from git diff)" },
      { stage: "patch", kind: "diff", log: '-  await page.click("#submit-btn");\n+  await page.click("#submit");' },
      {
        stage: "verify",
        kind: "log",
        log: "selector_verify_started   selector_count=1 url=http://localhost:4173\nselector_verify_passed    counts={'#submit': 1}\nast_lock_passed",
        note: "locatorOnly",
      },
      { stage: "run", kind: "log", log: "test_runner_passed        loop_count=0" },
      { stage: "end", kind: "healed", log: "fixed after 0 loop(s)", note: "assertionKept" },
    ],
  },
  "label-rename": {
    outcome: "refuse",
    reason: "insufficient_evidence",
    steps: [
      { stage: "diag", kind: "log", log: "diagnoser_finished", note: "labelNoEvidence" },
      { stage: "patch", kind: "log", log: "patch_generator_finished  instruction_count=0 (declined)", note: "noInventedName" },
      { stage: "run", kind: "fail", log: "test_runner_failed        loop_count=1 → 2 → 3" },
      { stage: "end", kind: "refused", log: "repair_refused  reason=insufficient_evidence", note: "incorrectRefusalCost" },
    ],
  },
  "delayed-cta": {
    outcome: "repair",
    steps: [
      { stage: "diag", kind: "log", log: "diagnoser_finished", note: "lateElement" },
      { stage: "patch", kind: "diff", log: '-  await page.click(".cta-primary");\n+  await page.click(".cta-primary", { timeout: 10_000 });' },
      { stage: "verify", kind: "log", log: "ast_lock_passed", note: "timeoutOnly" },
      { stage: "run", kind: "log", log: "test_runner_passed        loop_count=0" },
      { stage: "end", kind: "healed", log: "fixed after 0 loop(s)", note: "waitOnly" },
    ],
  },
  "wrapper-added": {
    outcome: "repair",
    steps: [
      { stage: "diag", kind: "log", log: "diagnoser_finished", note: "wrapperBrokeChild" },
      { stage: "patch", kind: "diff", log: '-  await page.click("form > button");\n+  await page.click("form button");' },
      { stage: "verify", kind: "log", log: "selector_verify_passed    counts={'form button': 1}\nast_lock_passed" },
      { stage: "run", kind: "log", log: "test_runner_passed        loop_count=0" },
      { stage: "end", kind: "healed", log: "fixed after 0 loop(s)" },
    ],
  },
  "split-submit": {
    outcome: "refuse",
    reason: "ambiguous_target",
    steps: [
      { stage: "diag", kind: "log", log: "diagnoser_finished", note: "twoCandidates" },
      { stage: "patch", kind: "diff", log: '-  await page.click("#submit-btn");\n+  await page.click("button.btn");' },
      { stage: "verify", kind: "fail", log: "selector_verify_failed    counts={'button.btn': 2}", note: "notExactlyOne" },
      { stage: "end", kind: "refused", log: "repair_refused  reason=ambiguous_target", note: "handedToHuman" },
    ],
  },
  "id-rename-submit-dropped": {
    outcome: "refuse",
    reason: "loop_cap_reached",
    steps: [
      { stage: "diag", kind: "log", log: "loop 0 · diagnoser_finished\n#submit-btn → id renamed" },
      { stage: "patch", kind: "diff", log: '-  await page.click("#submit-btn");\n+  await page.click("#submit");' },
      { stage: "verify", kind: "log", log: "selector_verify_passed    counts={'#submit': 1}" },
      {
        stage: "run",
        kind: "fail",
        log: 'test_runner_failed        loop_count=1\nexpect(getByText("Thanks!")).toBeVisible() failed',
        note: "clickedNotSubmitted",
      },
      {
        stage: "diag",
        kind: "log",
        log: "loop 1 · diagnoser_finished\npatch_generator_finished  instruction_count=0 (declined)",
        note: "assertionSideFailure",
      },
      { stage: "run", kind: "fail", log: "test_runner_failed        loop_count=2 → 3" },
      { stage: "end", kind: "refused", log: "repair_refused  reason=loop_cap_reached  (loop_count=3)", note: "noAssertionEdit" },
    ],
  },
  "disabled-submit": {
    outcome: "refuse",
    reason: "guardrail_violation",
    steps: [
      { stage: "diag", kind: "log", log: "diagnoser_finished", note: "foundButDisabled" },
      { stage: "patch", kind: "diff", log: '-  await page.click("#submit-btn");\n+  await page.click("#submit-btn", { force: true });' },
      {
        stage: "verify",
        kind: "fail",
        log: "ast_lock_rejected         reason=option key 'force' is not allowed  line=9\nPatchGuardrailViolation",
        note: "fedBackSpendsLoop",
      },
      { stage: "end", kind: "refused", log: "repair_refused  reason=guardrail_violation", note: "noForceClick" },
    ],
  },
  "wrong-base-url": {
    outcome: "refuse",
    reason: "insufficient_evidence",
    steps: [
      { stage: "diag", kind: "log", log: "diagnoser_finished", note: "navigationFailedFirst" },
      { stage: "end", kind: "refused", log: "repair_refused  reason=insufficient_evidence", note: "fixTheEnvironment" },
    ],
  },
  "classname-rename": { outcome: "repair" },
  "product-regression": { outcome: "refuse", reason: "loop_cap_reached" },
  "cta-rename-handler-dropped": { outcome: "refuse", reason: "loop_cap_reached" },
} satisfies Record<string, Run>;

export type ScenarioName = keyof typeof RUNS;
/** Scenarios shown in the player, i.e. the ones with steps; only these need translated text. */
export type PlayerName = { [K in ScenarioName]: (typeof RUNS)[K] extends { steps: Step[] } ? K : never }[ScenarioName];
export type PlayerScenario = ScenarioData & Run & { name: PlayerName; steps: Step[] };

export const playerScenarios: PlayerScenario[] = (Object.keys(RUNS) as ScenarioName[]).flatMap((name) => {
  const run: Run = RUNS[name];
  return run.steps ? [{ ...scenarioData[name], ...run, name: name as PlayerName, steps: run.steps }] : [];
});

export type BenchRow = { name: string; class: string; expected: Outcome; actual: Outcome };
export const benchRows: BenchRow[] = (Object.keys(RUNS) as ScenarioName[]).map((name) => ({
  name,
  class: scenarioData[name].class,
  expected: scenarioData[name].expected,
  actual: RUNS[name].outcome,
}));
